version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: development
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /.github/actions/discord_send_job_results
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /.github/actions/maven_deploy
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /.github/actions/maven_set_project_version
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /.github/actions/setup_workspace
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /.github/actions/sign_jars
    schedule:
      interval: weekly
