name: SonarCloud

on:
  push:
    branches: [ master, development ]
  workflow_dispatch:

permissions: read-all

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_ORGANIZATION: craftaro
  SONAR_PROJECT_KEY: craftaro_example_project  # TODO: Change this to your project key, can be configured in pom.xml in non-

jobs:
  Analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # TODO: Make sure the project doesn't need additional setup steps or change the action to your own.
      - name: Prepare Workspace
        uses: ./.github/actions/setup_workspace

      - name: 'Cache: SonarCloud'
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Analyze project
        run: >
          mvn -B \
            verify \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            "-Dsonar.organization=$SONAR_ORGANIZATION" \
            "-Dsonar.projectKey=$SONAR_PROJECT_KEY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
